volume uses pulseaudio now. update ow and sherlock

diff --git a/sherlock b/sherlock
--- a/sherlock
+++ b/sherlock
@@ -17,10 +17,10 @@ browser=chromium
 font=Cantarell-12
 sf_color=#ffffff # selected text
 sb_color=#427fed # selected background
-nf_color=#333333 # normal text
-nb_color=#f9f9f9 # normal background
+nf_color=#ffffff # normal text
+nb_color=#242424 # normal background
 height=28
-lines=10
+lines=5
 
 # position for dmenu (centered in the screen)
 xres=$(xdpyinfo | grep 'dimensions:' | awk '{print $2}' | cut -dx -f1)
@@ -233,7 +233,9 @@ run_google() {
     #     fi
     #     ;;
 
-    # umount)
+
+
+run_umount() {
 
     #     usb=$(mount | awk '$3 ~ /\/media\// || /\/mnt\// { print $3 }' | xdmenu "umount")
 
@@ -246,9 +248,59 @@ run_google() {
     #     else
     #         notify-send "Some apps are using $usb"
     #     fi
-    #     exit 0
-    #     ;;
 
+
+    target=( $(awk '/media\/[\^A-Z]/ {print $3}' <(mount)) )
+    #shares=(Safebox Scout Sentinel)
+
+    checkbusy() {
+        grep "PID" <(lsof +d "$target" &>/dev/null)
+        if [[ $? -eq 0 ]]; then
+            printf "%s\n" "${target##*/} busyâ€¦"
+            exit 1
+        fi
+    }
+
+    exstatus() {
+        if [[ $? -eq 0 ]]; then
+            printf "%s\n" "${target##*/} unmountedâ€¦"
+        else
+            printf "%s\n" "Failed to unmount."
+        fi
+    }
+
+    # check for multiple devices
+    if (( "${#target[@]}" > 1 )); then
+        choice=$(echo $target | xmenu "umount")
+    fi
+
+    # check for share
+    for drive in "${shares[@]}"; do
+        if [[ "$drive" = "${target##*/}" ]]; then
+            share="$drive"
+        fi
+    done
+
+    # options per filesystem
+    if [[ -n "$target" ]]; then
+        for drive in "${shares[@]}"; do
+            if [[ "$drive" = "${target##*/}" && "${target##*/}" = Safebox ]]; then
+                cmd=$(sudo safebox close)
+            elif [[ "$drive" = "${target##*/}" ]]; then
+                cmd=$(sudo umount "$target")
+        else
+                cmd=$(udiskie-umount -d "$target" &>/dev/null)
+            fi
+        done
+    # do it
+        checkbusy
+        # flush to disk
+        /usr/bin/sync && $cmd
+        exstatus
+    else
+    printf "%s\n" "No drive mounted!"
+    fi
+}
 
 option=""
 
@@ -256,7 +308,7 @@ option=""
 if [ $# -eq 0 ] ; then
     opts=("apps" "google" "explore" "power" "screen" "search" "calc")
 
-    choice=$(printf "%s\n" "${opts[@]}" | xdmenu "olgaaa")
+    choice=$(printf "%s\n" "${opts[@]}" | xdmenu "sherlock")
     if [ "$choice" == "" ] ; then
         exit 1
     else
@@ -269,7 +321,6 @@ else
 fi
 
 case "$option" in
-
     apps)    run_apps ;;
     power)   run_power ;;
     calc)    run_calc ;;
diff --git a/volume b/volume
--- a/volume
+++ b/volume
@@ -1,83 +1,75 @@
-#!/bin/bash
-# Usage: volume [up|down|toggle]
+#! /bin/bash
+#
+# Control pulseaudio volume (based on pulseaudio-ctl)
+#
 
-if [ $# -lt 1 ] ; then
-    echo "usage: volume [up|down|toggle]"
-    exit 1
-fi
+setup() {
+  sink=$(pacmd list-sinks | awk '/* index:/{ print $3 }')
+  muted=$(pacmd list-sinks | grep -A 15 '* index' | awk '/muted:/{ print $2 }')
+  vol=$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: 0:/{ print $3 }' | sed 's/%//')
 
-device="Master"
-
-to_grep="Mono: P"
-try=$(amixer get $device | grep "$to_grep")
-if [ ! $try ] ; then
-    to_grep="Front Left: P"
-fi
-
-# Increase/drecrease volume
-function increase_volume()
-{
-    amixer -q set $device $1%+
+  if [ "$vol" -ge 0 -o "$vol" -lt 0 2>/dev/null ]; then
+      return 0
+  else
+      # the git snapshot at the time of writing this script changes the
+      # expected output of this cmd
+      vol=$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: front/{ print $5 }' | sed 's/%//g')
+      if [ "$vol" -ge 0 -o "$vol" -lt 0 2>/dev/null ]; then
+          return 0
+      else
+          echo -e "Cannot find current volume."
+          exit 1
+      fi
+  fi
 }
 
-function decrease_volume()
-{
-    amixer -q set $device $1%-
-}
-
-# Gets the current volume
-function get_volume()
-{
-    curvol=$(amixer get $device | grep "$to_grep" | cut -d '[' -f 2 | cut -d '%' -f 1)
-    echo $curvol
-}
-
-# Get mute state
-function get_muted()
-{
-    ismuted=$(amixer get $device | grep "$to_grep" | awk '{print $6}' | sed -e 's:\[::' | sed -e 's:\]::')
-    echo $ismuted
-}
-
-vol=$(get_volume)    # Reads volume
-muted=$(get_muted)   # Reads mute
-
-if [[ $1 == "up" ]] ; then
-
-    if [[ $muted == "off" ]] ; then
-	    amixer -q set $device toggle
-    fi
-    
-    vol=$(($vol + 5))   
-    if [[ $vol -gt 100 ]] ; then
-        increase_volume $((100 - $vol + 5))
-        vol=100
-    else 
-	    increase_volume 5
-    fi
-
-elif [[ $1 == "down" ]] ; then
-    if [[ $muted == "off" ]] ; then
-	    amixer -q set $device toggle
-    fi
-
-    vol=$(($vol - 5))
-    if [[ $vol -le 0 ]]
-    then
-        decrease_volume $(($vol + 5))
-        vol=0        
+osd() {
+    setup
+    if [[ $muted == "yes" ]] ; then
+        osdify -p $vol -a
     else
-	    decrease_volume 5
+        osdify -p $vol
     fi
-elif [[ $1 == "toggle" ]] ; then
-    amixer -q set $device toggle
-fi
+}
 
-muted=$(get_muted)
+vol_up() {
+    [[ "$vol" -ge 100 ]] && return 0 ||
+    pactl set-sink-volume "$sink" -- +5%
+}
 
-if [[ $muted == "off" ]] ; then
-    osdify -p $vol -a
-else
-    osdify -p $vol
-fi
+vol_down() {
+    [[ "$vol" -le 0 ]] && return 0 ||
+    pactl set-sink-volume "$sink" -- -5%
+}
 
+toggle() {
+    pactl set-sink-mute "$sink" toggle
+}
+
+case "$1" in
+    up)
+        # raise volume by 5%
+        setup
+        [[ "$muted" == "yes" ]] && toggle
+        vol_up
+        osd
+        ;;
+    down)
+        # lowers volume by 5%
+        setup
+        [[ "$muted" == "yes" ]] && toggle
+        vol_down
+        osd
+        ;;
+    toggle)
+        # mutes the volume entirely
+        setup
+        toggle
+        osd
+        ;;
+    *)
+        # show usage
+        echo "volume [up|down|toggle]"
+        exit 1
+        ;;
+esac
